### ISSUE TITLE
How do I use it

### ISSUE THREAD

**Issue by Jamison9876** [iiFlamiinBlaze/BlazinHud#3]
The instructions on how to use this plugin are not very clear and I am confused on how to change the message

**Comment by iiFlamiinBlaze** [comment]
Change hud-message option in the config file to change the message

**Comment by Jamison9876** [comment]
Thanks BTW you are my fav dev you keep your plugs updated

**Comment by Jamison9876** [comment]
my

**Comment by iiFlamiinBlaze** [comment]
:D 👍
